version: 0.1

phases:
  build:
    commands:
      - echo Build completed on `date`
      - mvn install

artifacts:
  files:
    - appspec.yml
    - target/CRM.war
    - scripts/stop_server.sh
    - scripts/cleanup.sh
    - scripts/start_server.sh
